In [1]:
# Prepare the notebook
import pandas as pd
import plotly.express as px

# Used the 'thousands' argument as the dataset contains commas
bill = pd.read_csv('meralco_bills.csv', thousands=',')
bill = bill.rename(columns={
    'YEAR' : 'year',
    'MONTH' : 'month',
    'KWH CONSUMPTION' : 'kwh_cons',
    'AMOUNT DUE' : 'amt_due',
    'COST PER KWH ' : 'cost_per_kwh'
})
# Combine the year and month columns into a date type column 
bill['date'] = bill['year'].astype(str) + '-' + bill['month']

# Convert datatype into datetime
bill['date'] = pd.to_datetime(bill['date'], format='%Y-%B')

# Check if data type is correct
bill['date'].dtype

dtype('<M8[ns]')

In [2]:
# Preview the dataset
bill.head(12)

    year      month  kwh_cons  amt_due  cost_per_kwh       date
0   2022    January       NaN      NaN           NaN 2022-01-01
1   2022   February     137.0  1316.76         9.611 2022-02-01
2   2022      March      58.0   374.15         6.451 2022-03-01
3   2022      April       NaN      NaN           NaN 2022-04-01
4   2022        May     156.0  1570.51        10.067 2022-05-01
5   2022       June      69.0   480.22         6.960 2022-06-01
6   2022       July      69.0   448.85         6.505 2022-07-01
7   2022     August      66.0   421.06         6.380 2022-08-01
8   2022  September      82.0   572.61         6.983 2022-09-01
9   2022    October       NaN      NaN           NaN 2022-10-01
10  2022   November       NaN      NaN           NaN 2022-11-01
11  2022   December      61.0   416.38         6.826 2022-12-01

In [3]:
# Check the data types
bill.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   year          60 non-null     int64
 1   month         60 non-null     object
 2   kwh_cons      50 non-null     float64
 3   amt_due       50 non-null     float64
 4   cost_per_kwh  50 non-null     float64
 5   date          60 non-null     datetime64[ns]
dtypes: datetime64[ns](1), float64(3), int64(1), object(1)
memory usage: 2.9+ KB

### **1. Does my cost per kWh appear to be increasing or decreasing?**

In [11]:
# Visualize the dataset
figure1 = px.line(
    data_frame=bill,
    x = 'date',
    y = 'cost_per_kwh',
    #color='month',
    labels = {
        'date' : 'Month and Years',
        'cost_per_kwh' : 'Cost per kWh'
    },
    #markers = True,
    #text='cost_per_kwh',
    title = 'Monthly cost per kWh from 2022 to 2026'
)

# For manual control on labels
'''figure1.update_xaxes(
    dtick = 'M2',
    tickformat = '%b - %Y'
)'''

figure1.show()

In [7]:
yearly_avg_cost =  bill.groupby('year')['cost_per_kwh'].mean().reset_index()
display(yearly_avg_cost)

   year  cost_per_kwh
0  2022      7.472875
1  2023      8.455364
2  2024     11.645583
3  2025     12.936417
4  2026     14.246429

In [12]:
figure2 = px.line(
    data_frame = yearly_avg_cost,
    x = 'year',
    y = 'cost_per_kwh',
    labels= {
        'year':'Years',
        'cost_per_kwh':'Cost per kWh'
    },
    markers=True,
    #text='cost_per_kwh',
    title = 'Yearly Average Cost per kWh from 2022 to 2026'
    )


# Remove the .5 on X axis
figure2.update_xaxes(type = 'category')

figure2.show()

Based on the yearly average of the cost per kWh, the data shows an overall upward trend from 2022 to 2026. The average cost increased from ₱7.47/kWh in 2022 to ₱14.25/kWh in 2026. Although the monthly costs per kWh shows some fluctuations, the yearly average still increased each year.